basic:
    name: seod-688
    environments:
        production: 'https://thisoldhouse.com'
        staging: 'https://staging.thisoldhouse.com'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - '/heating-cooling/21018992/read-this-before-you-install-central-air-conditioning/?src=jpplatform'
        - '/doors/21019066/all-about-exterior-french-doors/?src=jpplatform'
        - '/gutters/21016457/how-to-install-rain-gutters/?src=jpplatform'
        - '/flooring/21016706/how-to-tile-a-floor/?src=jpplatform'
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
