basic:
    name: seod-688
    environments:
        production: 'https://thisoldhouse.com'
        staging: 'https://staging.thisoldhouse.com'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /heating-cooling/21018992/read-this-before-you-install-central-air-conditioning
        - /doors/21019066/all-about-exterior-french-doors
        - /gutters/21016457/how-to-install-rain-gutters
        - /flooring/21016706/how-to-tile-a-floor
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
